### ISSUE TITLE
Custom Toggle Icon

### ISSUE THREAD

**Issue by SashaCollins** [yaminncco/vue-sidebar-menu#139]
Is it possible to change/alternate the toggle-btn icon between collapsed states?
e.g. 
```scss
.vsm--toggle-btn {
&:after {
      content: '\f100';
      font-family: 'Font Awesome 5 Free';
    }
}
.vsm--toggle-btn  &.vsm_collapsed {
&:after {
      content: '\f101';
      font-family: 'Font Awesome 5 Free';
    }
```
or something similar, because this isn't working
