### ISSUE TITLE
Increase the width of child

### ISSUE THREAD

**Issue by ageevmark** [yaminncco/vue-sidebar-menu#279]
How can I increase the width of the block with child links when the sidebar is collapsed? I am adding the following in the component's styles:

.v-sidebar-menu .vsm--child {
  width: 500px !important;
}

But it doesn't help.

**Comment by yaminncco** [comment]
You could try

```css
.v-sidebar-menu .vsm--child_mobile {
  width: 500px !important;
}
.v-sidebar-menu .vsm--link_mobile .vsm--title {
  width: 500px !important;
}
.v-sidebar-menu .vsm--mobile-bg {
  /* width + sidebar width on collapse mode */
  width: calc(500px + 65px) !important;
}
```
