### ISSUE TITLE
Custom "collapse" icon place

### ISSUE THREAD

**Issue by lacivert** [yaminncco/vue-sidebar-menu#59]
How can we put the collapse button/icon to the upperside (or another place) of the menu?

**Comment by yaminncco** [comment]
you can change `.collapse-btn` css or you can toggle `collapsed` prop from a button outside the component

**Comment by lacivert** [comment]
Thank you very much

**Comment by Symbolk** [comment]
@yaminncco I find the css code for the collapsed button, but I do not know how to change it in the <style> of my vue file, can you help me? 
```css
<style>
.v-sidebar-menu .collapse-btn {
      display: block;
    text-align: center;
    font-style: normal;
    font-weight: 900;
    height: 50px;
    cursor: pointer;
    border: none;
    width: 100%;
    &:after {
      content: '\f337';
      font-family: 'Font Awesome 5 Free';
    }
    &.slot-icon:after {
      display: none;
    }
}
</style>
```
